version: '3'

services:

  webapp:
    image: 'freestl/pictureapp:3'
    container_name: webapp
    ports:
      - '8080:8080'
    networks:
      - test-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      - test-network

  ddos:
    image: utkudarilmaz/hping3:latest
    container_name: ddos
    command: --rand-source --verbose --flood host.docker.internal -p 8080
    #    command: --rand-source -S -q -n --flood host.docker.internal -p 80
    #    command: --rand-source --udp --flood host.docker.internal -p 80
    #    command: --rand-source -F --flood host.docker.internal -p 80
    #    command: --rand-source -R --flood host.docker.internal -p 80
    #    command: --rand-source -PA --flood host.docker.internal -p 80
    #    command: --rand-source -1 --verbose --flood host.docker.internal -p 80
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
